
<div style=" width:auto;  background:url(img/main_bglist.jpg) repeat-x #cccccc; height: 60px;">
<div style=" width:960px; height:60px; margin:auto; padding:8px;;"><!--link pages-->
 <h2><ul><a herf ="#">Support</a></ul></h2>
     <h3> <li><a href="#">Accdient report</a></li></h3>
 

</div>
</div>
<div style="width:auto; background: url(img/head_bgrigt.jpg) repeat-x; height:70px; ">
  <div class="footer">
    
    <h4>Copyright &copy; 2012 REUNION All rights reserved.</h4>
  </div>
</div>
</body>
</html>
